import type { GisServiceDef } from "./types";

export const BUILTIN_GIS_SERVICES: GisServiceDef[] = [
  // كنوز مصر (خامسة ابتدائي) — طبقات جاهزة وبتشتغل تلقائيًا
  {
    id: "egypt_resource_map",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "خريطة مصر التعليمية (حدود/طرق/مأهول)",
    description: "حدود مصر + شبكة طرق + أماكن مأهولة",
    url: "https://services1.arcgis.com/0MSEUqKaxRlEPj5g/ArcGIS/rest/services/Eygpt_Resource_Map_WFL1/FeatureServer",
    defaultLayerIds: [0, 1, 3, 4],
    enabledByDefault: true,
    defaultOpacity: 0.55,
    minZoom: 6,
    source: "ArcGIS Online",
  },
  {
    id: "minerals_africa_egypt",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "معادن مصر (نظرة عامة)",
    description: "مواقع/مناطق معادن داخل مصر (من Minerals_Africa)",
    url: "https://services3.arcgis.com/ixehHGhSDmBKeOyS/arcgis/rest/services/Minerals_Africa/FeatureServer",
    defaultLayerIds: [0],
    defaultWhereByLayerId: { 0: "FIPS_CNTRY = 'EG'" },
    enabledByDefault: true,
    defaultOpacity: 0.5,
    minZoom: 7,
    source: "ArcGIS Online",
  },
  {
    id: "mrds_compact",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "مناجم/تمعدنات (MRDS)",
    description: "قاعدة عالمية للمناجم والتمعدنات (تظهر داخل مصر عند التكبير)",
    url: "https://services.arcgis.com/v01gqwM5QqNysAAi/arcgis/rest/services/Mineral_Resources_Data_System_MRDS_Compact_Version/FeatureServer",
    defaultLayerIds: [0],
    enabledByDefault: true,
    defaultOpacity: 0.75,
    minZoom: 8,
    source: "MRDS (ArcGIS Online)",
  },
  {
    id: "geology_nubian_project",
    kind: "arcgis",
    serviceType: "MapServer",
    label: "الخريطة الجيولوجية (Nubian Project)",
    description: "طبقة جيولوجية تساعد تربط المعادن بأنواع الصخور (Layer 26)",
    url: "https://www.esrs.wmich.edu/arcgis/rest/services/Nubian_project/MapServer",
    defaultLayerIds: [26],
    enabledByDefault: true,
    defaultOpacity: 0.35,
    minZoom: 7,
    source: "esrs.wmich.edu",
  },
  {
    id: "world_power_plants_egypt",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "محطات الكهرباء في مصر",
    description: "محطات توليد الكهرباء + نوع الوقود (غاز/مياه/رياح/شمس...)",
    url: "https://services.arcgis.com/jIL9msH9OI208GCb/arcgis/rest/services/GlobalPowerPlants/FeatureServer",
    defaultLayerIds: [0],
    defaultWhereByLayerId: { 0: "country_long = 'Egypt'" },
    enabledByDefault: true,
    defaultOpacity: 0.85,
    minZoom: 7,
    source: "WRI (ArcGIS Online)",
  },
  {
    id: "egcapital_egypt_user",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "EGCapitalGIS - egypt_user",
    description: "بيانات قطاعية/حدود محافظات (Hosted/egypt_user)",
    url: "https://egcapitalgis.idsc.gov.eg/server/rest/services/Hosted/egypt_user/FeatureServer",
    defaultLayerIds: [7],
    enabledByDefault: false,
    minZoom: 5,
    source: "egcapitalgis.idsc.gov.eg",
  },
  {
    id: "hydro_egypt",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "Hydro_Egypt",
    description: "بيانات هيدرولوجية لمصر",
    url: "https://pro-ags2.dfs.un.org/arcgis/rest/services/hosted/Hydro_Egypt/FeatureServer",
    defaultLayerIds: [0],
    enabledByDefault: true,
    defaultOpacity: 0.55,
    minZoom: 6,
    source: "dfs.un.org",
  },
  {
    id: "egypt_water_bodies",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "Egypt Water Bodies",
    description: "مسطحات مائية (بحر/نيل)",
    url: "https://gis.wfp.org/arcgis/rest/services/Hosted/Egypt_Water_Bodies/FeatureServer",
    defaultLayerIds: [8, 9],
    enabledByDefault: true,
    defaultOpacity: 0.6,
    minZoom: 6,
    source: "gis.wfp.org",
  },
  {
    id: "egypt_scrub_forest",
    kind: "arcgis",
    serviceType: "FeatureServer",
    label: "Egypt Scrub and Forest",
    description: "غطاء نباتي (غابات/شجيرات)",
    url: "https://services5.arcgis.com/SaBe5HMtmnbqSWlu/ArcGIS/rest/services/Egypt_Scrub_and_Forest/FeatureServer",
    defaultLayerIds: [2],
    enabledByDefault: true,
    defaultOpacity: 0.4,
    minZoom: 6,
    source: "ArcGIS Online",
  },
  {
    id: "cairo_gov_boundaries",
    kind: "arcgis",
    serviceType: "MapServer",
    label: "محافظة القاهرة بالحدود",
    description: "حدود محافظة القاهرة (وأحياء/شياخات/نيل...)",
    url: "https://geoportal.cairodc.gov.eg/server/rest/services/محافظة_القاهرة_بالحدود/MapServer",
    defaultLayerIds: [0, 1, 2, 3, 4],
    enabledByDefault: false,
    minZoom: 9,
    source: "geoportal.cairodc.gov.eg",
  },
  {
    id: "cairo_gamaleya_services",
    kind: "arcgis",
    serviceType: "MapServer",
    label: "خدمات حي الجمالية",
    description: "خدمات (بنوك/مدارس/مستشفيات...)",
    url: "https://geoportal.cairodc.gov.eg/server/rest/services/خدمات_الجمالية/MapServer",
    defaultLayerIds: [0, 1, 2, 3, 4, 5, 6, 7],
    enabledByDefault: false,
    minZoom: 12,
    source: "geoportal.cairodc.gov.eg",
  },
  {
    id: "cairo_maadi_services",
    kind: "arcgis",
    serviceType: "MapServer",
    label: "خدمات حي المعادي",
    description: "خدمات (نوادي وخدمات أخرى)",
    url: "https://geoportal.cairodc.gov.eg/server/rest/services/خدمات_حى_المعادى/MapServer",
    defaultLayerIds: [0, 1, 2, 3, 4, 5, 6, 7],
    enabledByDefault: false,
    minZoom: 12,
    source: "geoportal.cairodc.gov.eg",
  },
  {
    id: "isric_farming_systems_wms",
    kind: "wms",
    label: "ISRIC - Farming Systems (WMS)",
    description: "أنظمة الزراعة في إفريقيا (يمكن التكبير على مصر)",
    url: "https://africasis.isric.org/ows/farming-systems",
    version: "1.3.0",
    transparent: true,
    format: "image/png",
    defaultLayers: ["fs_lev_2_distribution"],
    enabledByDefault: false,
    minZoom: 5,
    source: "africasis.isric.org",
  },
  // روابط إضافية من القائمة (متاحة للكبار / قد تحتاج صلاحيات)
  {
    id: "mwri_root",
    kind: "arcgis-root",
    label: "MWRI Geoportal (Root)",
    description: "بوابة وزارة الموارد المائية والري (قد تحتاج صلاحيات دخول)",
    url: "https://geoportal.mwri.gov.eg/server/rest/services",
    source: "geoportal.mwri.gov.eg",
  },
  // Root catalogs (للاستعراض داخل التطبيق)
  {
    id: "idsc_egis_hosted_root",
    kind: "arcgis-root",
    label: "IDSC EGIS - Hosted (Root)",
    description: "جذر خدمات مركز معلومات مجلس الوزراء (Hosted)",
    url: "https://www.egis.idsc.gov.eg/server/rest/services/Hosted",
    source: "egis.idsc.gov.eg",
  },
  {
    id: "egcapitalgis_root",
    kind: "arcgis-root",
    label: "EGCapitalGIS - Root",
    description: "جذر EGCapitalGIS",
    url: "https://egcapitalgis.idsc.gov.eg/server/rest/services",
    source: "egcapitalgis.idsc.gov.eg",
  },
  {
    id: "geoportal_cairo_root",
    kind: "arcgis-root",
    label: "Geoportal Cairo - Root",
    description: "جذر خدمات ArcGIS Server لبوابة القاهرة",
    url: "https://geoportal.cairodc.gov.eg/server/rest/services",
    source: "geoportal.cairodc.gov.eg",
  },
  // FAO WMS endpoint كان بيرجع 404 وقت التجربة، فموجود هنا كخيار يدوي
  {
    id: "fao_wms_root",
    kind: "wms",
    label: "FAO GeoServer - Base WMS",
    description: "سيرفر WMS من FAO (قد يحتاج تحديث الرابط)",
    url: "http://data.fao.org/maps/ows",
    version: "1.3.0",
    transparent: true,
    format: "image/png",
    defaultLayers: [],
    enabledByDefault: false,
    minZoom: 4,
    source: "data.fao.org",
  },
];
